# Generated by Django 2.0.13 on 2019-05-15 13:09

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import research.models.dataset


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextDataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=150)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('source', models.FileField(upload_to=research.models.dataset.dataset_directory_path)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('storage_path', models.CharField(max_length=500)),
                ('identity_column_index', models.IntegerField()),
                ('header_row_index', models.IntegerField()),
                ('values_separator_character', models.CharField(max_length=5)),
                ('research', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_datasets', related_query_name='text_dataset', to='research.Research')),
            ],
            options={
                'verbose_name': 'dataset',
                'verbose_name_plural': 'datasets',
                'ordering': ['-creation_date'],
                'abstract': False,
            },
        ),
        migrations.AlterUniqueTogether(
            name='textdataset',
            unique_together={('slug', 'research')},
        ),
    ]
