# Generated by Django 2.0.13 on 2019-06-05 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='research',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
