# Generated by Django 2.0.13 on 2019-05-14 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='plot',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='window',
            name='plot',
            field=models.ImageField(max_length=600, upload_to=''),
        ),
    ]
