# Generated by Django 2.0.13 on 2019-04-16 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='file_type',
            field=models.CharField(choices=[('Text file', 'TEXT'), ('EDF file', 'EDF')], max_length=10),
        ),
    ]
