# Generated by Django 2.0.13 on 2019-05-27 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filtrationwindow',
            name='end',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='filtrationwindow',
            name='start',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mapperwindow',
            name='end',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mapperwindow',
            name='start',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
