# Generated by Django 2.0.13 on 2019-05-06 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filtrationanalysis',
            name='max_distances_considered',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='filtrationanalysis',
            name='n_perm',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
