# Generated by Django 2.0.13 on 2019-05-27 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='plot',
            field=models.TextField(blank=True, null=True),
        ),
    ]
