# Generated by Django 2.0.13 on 2019-05-15 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filtrationanalysis',
            name='precomputed_distance_matrix',
            field=models.FileField(blank=True, default=None, null=True, upload_to='research/precomputed/'),
        ),
    ]
