# Generated by Django 2.0.13 on 2019-05-28 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0002_auto_20190527_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='cols',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dataset',
            name='rows',
            field=models.PositiveIntegerField(default=1000),
            preserve_default=False,
        ),
    ]
