# Generated by Django 2.0.13 on 2019-04-24 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0002_auto_20190424_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='plot',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
