# Generated by Django 2.0.13 on 2019-05-08 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0002_auto_20190507_2004'),
        ('research', '0002_auto_20190506_1645'),
    ]

    operations = [
    ]
