# Generated by Django 2.0.13 on 2019-05-15 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0002_auto_20190515_1632'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapperAnalysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=110)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('distance_matrix_metric', models.CharField(choices=[('braycurtis', 'Braycurtis'), ('canberra', 'Canberra'), ('chebyshev', 'Chebyshev'), ('cityblock', 'City block'), ('correlation', 'Correlation'), ('cosine', 'Cosine'), ('dice', 'Dice'), ('euclidean', 'Euclidean'), ('hamming', 'Hamming'), ('jaccard', 'Jaccard'), ('jensenshannon', 'Jensen Shannon'), ('kulsinski', 'Kulsinski'), ('mahalanobis', 'Mahalonobis'), ('matching', 'Matching'), ('minkowski', 'Minkowski'), ('rogerstanimoto', 'Rogers-Tanimoto'), ('russellrao', 'Russel Rao'), ('seuclidean', 'Seuclidean'), ('sokalmichener', 'Sojal-Michener'), ('sokalsneath', 'Sokal-Sneath'), ('sqeuclidean', 'Sqeuclidean'), ('yule', 'Yule')], default='euclidean', max_length=20)),
                ('precomputed_distance_matrix', models.FileField(blank=True, default=None, null=True, upload_to='research/precomputed/')),
                ('window_size', models.IntegerField(blank=True, default=None, null=True)),
                ('window_overlap', models.IntegerField(default=0)),
                ('projection', models.CharField(choices=[('sum', 'Sum'), ('mean', 'Mean'), ('median', 'Median'), ('max', 'Max'), ('min', 'Min'), ('std', 'Std'), ('dist_mean', 'Dist_mean'), ('l2norm', 'L2norm'), ('knn_distance_n', 'knn_distance_n')], max_length=50)),
                ('scaler', models.CharField(choices=[('None', 'None'), ('MinMaxScaler', 'MinMaxScaler'), ('MaxAbsScaler', 'MaxAbsScaler'), ('RobustScaler', 'RobustScaler'), ('StandardScaler', 'StandardScaler')], max_length=50)),
                ('use_original_data', models.BooleanField(default=False)),
                ('clusterer', models.CharField(choices=[('k-means', 'K-Means'), ('affinity_propagation', 'Affinity propagation'), ('mean-shift', 'Mean-shift'), ('spectral_clustering', 'Spectral clustering'), ('agglomerative_clustering', 'StandardScaler'), ('DBSCAN', 'DBSCAN'), ('gaussian_mixtures', 'Gaussian mixtures'), ('birch', 'Birch')], default='DBSCAN', max_length=50)),
                ('cover_n_cubes', models.IntegerField(default=10)),
                ('cover_perc_overlap', models.FloatField(default=0.5)),
                ('graph_nerve_min_intersection', models.IntegerField(default=1)),
                ('remove_duplicate_nodes', models.BooleanField(default=False)),
                ('graph', models.TextField(blank=True, null=True)),
                ('dataset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mapperanalysis_requests_created', related_query_name='analysis', to='research.Dataset')),
                ('research', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mapperanalysis_requests_created', related_query_name='analysis', to='research.Research')),
            ],
            options={
                'verbose_name': 'mapper algorithm analysis',
                'verbose_name_plural': 'mapper algoritms analysis',
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='filtrationanalysis',
            name='dataset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filtrationanalysis_requests_created', related_query_name='analysis', to='research.Dataset'),
        ),
        migrations.AlterField(
            model_name='filtrationanalysis',
            name='research',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filtrationanalysis_requests_created', related_query_name='analysis', to='research.Research'),
        ),
        migrations.AlterUniqueTogether(
            name='mapperanalysis',
            unique_together={('slug', 'research')},
        ),
    ]
