# Generated by Django 2.0.13 on 2019-05-15 14:16

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import research.models.dataset


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0002_auto_20190515_1509'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=150)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('source', models.FileField(upload_to=research.models.dataset.dataset_directory_path)),
                ('source_type', models.CharField(choices=[('EDF', 'EDF file'), ('TXT', 'Text file')], max_length=3)),
                ('storage_path', models.CharField(max_length=500)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('research', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_datasets', related_query_name='text_dataset', to='research.Research')),
            ],
            options={
                'verbose_name': 'dataset',
                'verbose_name_plural': 'datasets',
                'ordering': ['-creation_date'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='textdataset',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='textdataset',
            name='research',
        ),
        migrations.DeleteModel(
            name='TextDataset',
        ),
        migrations.AlterUniqueTogether(
            name='dataset',
            unique_together={('slug', 'research')},
        ),
        migrations.CreateModel(
            name='TextDataset',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('research.dataset',),
        ),
    ]
