# Generated by Django 2.0.13 on 2019-05-15 14:18

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0003_auto_20190515_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='source_type',
            field=models.CharField(choices=[('TXT', 'Text')], max_length=3),
        ),
    ]
