# Generated by Django 2.0.13 on 2019-05-08 21:56

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0003_merge_20190508_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='filtrationanalysis',
            name='result_entropy',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='filtrationanalysis',
            name='window_overlap',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='filtrationanalysis',
            name='window_size',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
