# Generated by Django 2.0.13 on 2019-05-28 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0003_auto_20190528_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='cols',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='rows',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
