# Generated by Django 2.0.13 on 2019-05-28 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0004_auto_20190528_0902'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapperanalysis',
            name='precomputed',
            field=models.BooleanField(default=False, help_text='Tell Mapper whether the data that you are clustering on\n                                      is a precomputed distance matrix. If set to True, the assumption is that you are\n                                      also telling your clusterer that metric=’precomputed’ (which is an argument for\n                                      DBSCAN among others), which will then cause the clusterer to expect a square\n                                      distance matrix for each hypercube. precomputed=True will give a square matrix\n                                      to the clusterer to fit on for each hypercube.'),
        ),
    ]
