# Generated by Django 2.0.13 on 2019-06-28 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filtrationwindow',
            name='diagrams',
        ),
        migrations.AddField(
            model_name='filtrationwindow',
            name='diagram',
            field=models.TextField(blank=True, null=True),
        ),
    ]
