# Generated by Django 2.0.13 on 2019-06-04 06:53

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filtrationwindow',
            old_name='result_matrix',
            new_name='downloadable_output',
        ),
        migrations.RemoveField(
            model_name='filtrationanalysis',
            name='result_entropy',
        ),
        migrations.RemoveField(
            model_name='filtrationanalysis',
            name='result_matrix',
        ),
        migrations.RemoveField(
            model_name='filtrationanalysis',
            name='result_plot',
        ),
        migrations.RemoveField(
            model_name='filtrationwindow',
            name='result_plot',
        ),
        migrations.RemoveField(
            model_name='mapperanalysis',
            name='graph',
        ),
        migrations.AddField(
            model_name='filtrationwindow',
            name='diagrams',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mapperanalysis',
            name='projection',
            field=models.CharField(choices=[('sum', 'Sum'), ('mean', 'Mean'), ('median', 'Median'), ('max', 'Max'), ('min', 'Min'), ('std', 'Std'), ('dist_mean', 'Dist_mean'), ('l2norm', 'L2norm'), ('knn_distance_n', 'knn_distance_n')], default='sum', help_text='Specify a projection/lens type.', max_length=50),
        ),
        migrations.AlterField(
            model_name='mapperanalysis',
            name='scaler',
            field=models.CharField(choices=[('None', 'None'), ('MinMaxScaler', 'MinMaxScaler'), ('MaxAbsScaler', 'MaxAbsScaler'), ('RobustScaler', 'RobustScaler'), ('StandardScaler', 'StandardScaler')], default='MinMaxScaler', help_text='Scaler of the data applied after mapping. Use None for no scaling.', max_length=50),
        ),
    ]
