# Generated by Django 2.0.13 on 2019-06-06 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapperanalysis',
            name='knn_n_value',
            field=models.PositiveIntegerField(blank=True, help_text='Specify the value of n in knn_distance_n', null=True),
        ),
        migrations.AlterField(
            model_name='mapperanalysis',
            name='cover_n_cubes',
            field=models.PositiveIntegerField(default=10, help_text='Number of hypercubes along each dimension.\n                                        Sometimes referred to as resolution.'),
        ),
    ]
