# Generated by Django 2.0.13 on 2019-06-04 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_auto_20190604_0853'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filtrationwindow',
            old_name='diagrams',
            new_name='result_matrix',
        ),
        migrations.RemoveField(
            model_name='filtrationwindow',
            name='downloadable_output',
        ),
        migrations.AddField(
            model_name='filtrationwindow',
            name='result_plot',
            field=models.ImageField(blank=True, max_length=300, null=True, upload_to=''),
        ),
    ]
