# Generated by Django 2.0.13 on 2019-06-11 13:50

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_auto_20190606_0955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filtrationanalysis',
            name='precomputed_distance_matrix',
        ),
        migrations.RemoveField(
            model_name='mapperanalysis',
            name='precomputed_distance_matrix',
        ),
        migrations.AddField(
            model_name='filtrationanalysis',
            name='precomputed_distance_matrix_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mapperanalysis',
            name='precomputed_distance_matrix_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
