# Generated by Django 2.0.13 on 2019-06-11 13:57

import analysis.models.analysis
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_auto_20190611_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='filtrationanalysis',
            name='precomputed_distance_matrix',
            field=models.FileField(blank=True, default=None, help_text='Upload a precomputed distance matrix\n                                                   instead of selecting a dataset', null=True, upload_to=analysis.models.analysis.Analysis.precomputed_directory_path),
        ),
        migrations.AddField(
            model_name='mapperanalysis',
            name='precomputed_distance_matrix',
            field=models.FileField(blank=True, default=None, help_text='Upload a precomputed distance matrix\n                                                   instead of selecting a dataset', null=True, upload_to=analysis.models.analysis.Analysis.precomputed_directory_path),
        ),
    ]
