# Generated by Django 2.0.13 on 2019-06-11 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0004_auto_20190611_1557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filtrationanalysis',
            name='precomputed_distance_matrix',
        ),
        migrations.RemoveField(
            model_name='mapperanalysis',
            name='precomputed_distance_matrix',
        ),
    ]
