# Generated by Django 2.0.13 on 2019-06-11 19:30

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0005_auto_20190611_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='filtrationwindow',
            name='bottleneck_distance_versus_all',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='filtrationwindow',
            name='bottleneck_distance_versus_all_diags',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
