# Generated by Django 2.0.13 on 2019-06-18 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0007_auto_20190612_2155'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bottleneck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homology', models.PositiveIntegerField()),
                ('kind', models.CharField(choices=[('consecutive', 'consecutive'), ('one_to_all', 'one_to_all'), ('all_to_all', 'all_to_all')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Diagram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.TextField()),
                ('bottleneck_distance', models.FloatField()),
                ('bottleneck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.Bottleneck')),
            ],
        ),
        migrations.RemoveField(
            model_name='filtrationanalysis',
            name='bottleneck_distance_consecutive',
        ),
        migrations.RemoveField(
            model_name='filtrationanalysis',
            name='bottleneck_distance_consecutive_diags',
        ),
        migrations.RemoveField(
            model_name='filtrationwindow',
            name='bottleneck_distance_versus_all',
        ),
        migrations.RemoveField(
            model_name='filtrationwindow',
            name='bottleneck_distance_versus_all_diags',
        ),
        migrations.AlterField(
            model_name='filtrationanalysis',
            name='dataset',
            field=models.ForeignKey(blank=True, help_text='Select the source dataset from the loaded datasets', null=True, on_delete=django.db.models.deletion.CASCADE, to='datasets.Dataset'),
        ),
        migrations.AlterField(
            model_name='filtrationanalysis',
            name='research',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='research.Research'),
        ),
        migrations.AlterField(
            model_name='filtrationwindow',
            name='analysis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.FiltrationAnalysis'),
        ),
        migrations.AlterField(
            model_name='mapperanalysis',
            name='clusterer',
            field=models.CharField(choices=[('k-means', 'K-Means'), ('affinity_propagation', 'Affinity propagation'), ('mean-shift', 'Mean-shift'), ('spectral_clustering', 'Spectral clustering'), ('agglomerative_clustering', 'StandardScaler'), ('DBSCAN(min_samples=1)', 'DBSCAN(min_samples=1)'), ('DBSCAN(default)', 'DBSCAN(default)'), ('gaussian_mixtures', 'Gaussian mixtures'), ('birch', 'Birch')], default='DBSCAN', help_text='Select the clustering algorithm.', max_length=50),
        ),
        migrations.AlterField(
            model_name='mapperanalysis',
            name='dataset',
            field=models.ForeignKey(blank=True, help_text='Select the source dataset from the loaded datasets', null=True, on_delete=django.db.models.deletion.CASCADE, to='datasets.Dataset'),
        ),
        migrations.AlterField(
            model_name='mapperanalysis',
            name='research',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='research.Research'),
        ),
        migrations.AddField(
            model_name='diagram',
            name='window1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='window1', to='analysis.FiltrationWindow'),
        ),
        migrations.AddField(
            model_name='diagram',
            name='window2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='window2', to='analysis.FiltrationWindow'),
        ),
        migrations.AddField(
            model_name='bottleneck',
            name='analysis',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='analysis.FiltrationAnalysis'),
        ),
        migrations.AddField(
            model_name='bottleneck',
            name='window',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='analysis.FiltrationWindow'),
        ),
    ]
